In [11]:
import pandas as pd
import numpy as np

In [12]:
df= pd.read_csv('movies_metadata.csv',nrows=5000)

In [13]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173

In [14]:
df=df[['id','title','genres','overview']]

In [15]:
df.head()

,id,title,genres,overview
0,862,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...

In [16]:
df.shape

(5000, 4)

In [17]:
df.isnull().sum()

id           0
title        0
genres       0
overview    21
dtype: int64

In [18]:
df['overview']=df['overview'].fillna(' ')

In [19]:
df.duplicated().sum()

np.int64(1)

In [20]:
df.drop_duplicates(inplace=True)

In [21]:
df.sample(9)

,id,title,genres,overview
3462,1058,Breathless,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","Jesse has to get out of Las Vegas quickly, and..."
1821,56164,Cavalcade,"[{'id': 18, 'name': 'Drama'}]",A cavalcade of English life from New Year's Ev...
503,9800,Philadelphia,"[{'id': 18, 'name': 'Drama'}]",No one would take his case until one man was w...
601,25059,Homeward Bound II: Lost in San Francisco,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",Your favorite talking animals are back! The fi...
3723,20850,Ilsa: She Wolf of the SS,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",Ilsa is a warden at a Nazi death camp that con...
1824,43278,The Life of Emile Zola,"[{'id': 18, 'name': 'Drama'}]",Bio epic of the famous writer.
3528,42002,Anguish,"[{'id': 80, 'name': 'Crime'}, {'id': 27, 'name...",This gruesome horror film is about a mother-fi...
143,30765,The Amazing Panda Adventure,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Far from home in the lush bamboo forests of Ch...
4374,26386,Ernest Saves Christmas,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",When Santa Claus decides to retire and pass on...

In [22]:
df['genres'].value_counts(0)

genres
[{'id': 18, 'name': 'Drama'}]                                                                                                               437
[{'id': 35, 'name': 'Comedy'}]                                                                                                              285
[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]                                                                             232
[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}]                                                                                 187
[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]                                                                            164
                                                                                                                                           ...
[{'id': 12, 'name': 'Adventure'}, {'id': 35, 'name': 'Comedy'}, {'id': 36, 'name': 'History'}, {'id': 10749, 'name': 'Romance'}]              1
[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'name': 'Crime'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 53, 'name': 'Thriller'}]           1
[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'name': 'Horror'}, {'id': 28, 'name': 'Action'}]                                                  1
[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}, {'id': 14, 'name': 'Fantasy'}]                                                 1
[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'name': 'Horror'}, {'id': 10749, 'name': 'Romance'}, {'id': 878, 'name': 'Science Fiction'}]      1
Name: count, Length: 1089, dtype: int64

In [23]:
df['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [24]:
df=df.replace(r'\[|\]','',regex=True)
df.head(1)

,id,title,genres,overview
0,862,Toy Story,"{'id': 16, 'name': 'Animation'}, {'id': 35, 'n...","Led by Woody, Andy's toys live happily in his ..."

In [25]:
print(type(df['genres'].iloc[0]))

<class 'str'>

In [26]:
import ast
ast.literal_eval

In [27]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [28]:
df['genres'][0]

"{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}"

In [29]:
new_df=df[['id','title','genres','overview']]
new_df.head()

,id,title,genres,overview
0,862,Toy Story,"{'id': 16, 'name': 'Animation'}, {'id': 35, 'n...","Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,"{'id': 12, 'name': 'Adventure'}, {'id': 14, 'n...",When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,"{'id': 10749, 'name': 'Romance'}, {'id': 35, '...",A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name...","Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,"{'id': 35, 'name': 'Comedy'}",Just when George Banks has recovered from his ...

In [30]:
df['genres'][0]

"{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}"

In [31]:
df['genres']=df['genres'].astype(str)

In [32]:
df['genres'][0]

"{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}"

In [33]:
df['new_tags']=df['genres']+['overview']

In [34]:
df.head()

,id,title,genres,overview,new_tags
0,862,Toy Story,"{'id': 16, 'name': 'Animation'}, {'id': 35, 'n...","Led by Woody, Andy's toys live happily in his ...","{'id': 16, 'name': 'Animation'}, {'id': 35, 'n..."
1,8844,Jumanji,"{'id': 12, 'name': 'Adventure'}, {'id': 14, 'n...",When siblings Judy and Peter discover an encha...,"{'id': 12, 'name': 'Adventure'}, {'id': 14, 'n..."
2,15602,Grumpier Old Men,"{'id': 10749, 'name': 'Romance'}, {'id': 35, '...",A family wedding reignites the ancient feud be...,"{'id': 10749, 'name': 'Romance'}, {'id': 35, '..."
3,31357,Waiting to Exhale,"{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name...","Cheated on, mistreated and stepped on, the wom...","{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name..."
4,11862,Father of the Bride Part II,"{'id': 35, 'name': 'Comedy'}",Just when George Banks has recovered from his ...,"{'id': 35, 'name': 'Comedy'}overview"

In [35]:
new_df=df[['id','title','new_tags']]
new_df=new_df.replace(r'\[|\]','',regex=True)

In [36]:
new_df.head()

,id,title,new_tags
0,862,Toy Story,"{'id': 16, 'name': 'Animation'}, {'id': 35, 'n..."
1,8844,Jumanji,"{'id': 12, 'name': 'Adventure'}, {'id': 14, 'n..."
2,15602,Grumpier Old Men,"{'id': 10749, 'name': 'Romance'}, {'id': 35, '..."
3,31357,Waiting to Exhale,"{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name..."
4,11862,Father of the Bride Part II,"{'id': 35, 'name': 'Comedy'}overview"

In [37]:
new_df['new_tags'][1]

"{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}overview"

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500,stop_words='english')

In [39]:
vectors = cv.fit_transform(new_df['new_tags']).toarray()

In [40]:
vectors[0]

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [41]:
cv.get_feature_names_out()

array(['10402', '10749', '10751', '10752', '10769', '10770', '12', '14',
       '16', '18', '27', '28', '35', '36', '37', '53', '80', '878',
       '9648', '99', 'action', 'adventure', 'animation', 'comedy',
       'crime', 'documentary', 'drama', 'family', 'fantasy', 'fiction',
       'foreign', 'history', 'horror', 'id', 'movie', 'music', 'mystery',
       'overview', 'romance', 'science', 'thriller', 'tv', 'war',
       'western'], dtype=object)

In [42]:
import nltk

In [43]:
from nltk.stem.porter import PorterStemmer

In [44]:
ps=PorterStemmer()

In [45]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return" ".join(y)

In [46]:
new_df['new_tags']=new_df['new_tags'].apply(stem)

In [47]:
ps.stem('acting')

'act'

In [48]:
stem("'adventure', 'fantasy', 'family'when siblings judy and peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite alan -- an adult who's been trapped inside the game for 26 years -- into their living room. alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures."
)

"'adventure', 'fantasy', 'family'when sibl judi and peter discov an enchant board game that open the door to a magic world, they unwittingli invit alan -- an adult who' been trap insid the game for 26 year -- into their live room. alan' onli hope for freedom is to finish the game, which prove riski as all three find themselv run from giant rhinoceroses, evil monkey and other terrifi creatures."

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
similarity=cosine_similarity(vectors)

In [51]:
similarity[0]

array([1.   , 0.75 , 0.75 , ..., 0.625, 0.75 , 0.625], shape=(4999,))

In [52]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(695, np.float64(1.0)),
 (727, np.float64(1.0)),
 (1110, np.float64(1.0)),
 (1717, np.float64(1.0)),
 (1938, np.float64(1.0))]

In [53]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [54]:
recommend('Jumanji')

The Indian in the Cupboard
The Wizard of Oz
Labyrinth
Return to Oz
Harry Potter and the Philosopher's Stone

In [62]:
import pickle

In [63]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [64]:
new_df['title'].values

array(['Toy Story', 'Jumanji', 'Grumpier Old Men', ...,
       'Queen of the Damned', 'Big Bad Love', 'Green Dragon'],
      shape=(4999,), dtype=object)

In [65]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [66]:
new_df.to_dict()

{'id': {0: 862,
  1: 8844,
  2: 15602,
  3: 31357,
  4: 11862,
  5: 949,
  6: 11860,
  7: 45325,
  8: 9091,
  9: 710,
  10: 9087,
  11: 12110,
  12: 21032,
  13: 10858,
  14: 1408,
  15: 524,
  16: 4584,
  17: 5,
  18: 9273,
  19: 11517,
  20: 8012,
  21: 1710,
  22: 9691,
  23: 12665,
  24: 451,
  25: 16420,
  26: 9263,
  27: 17015,
  28: 902,
  29: 37557,
  30: 9909,
  31: 63,
  32: 78802,
  33: 9598,
  34: 47018,
  35: 687,
  36: 139405,
  37: 33689,
  38: 9603,
  39: 34615,
  40: 31174,
  41: 11443,
  42: 35196,
  43: 9312,
  44: 577,
  45: 11861,
  46: 807,
  47: 10530,
  48: 8391,
  49: 629,
  50: 117164,
  51: 11448,
  52: 49133,
  53: 26441,
  54: 97406,
  55: 124057,
  56: 9089,
  57: 11010,
  58: 99040,
  59: 11359,
  60: 17182,
  61: 2054,
  62: 10607,
  63: 19760,
  64: 9536,
  65: 11525,
  66: 40628,
  67: 4482,
  68: 10634,
  69: 755,
  70: 11859,
  71: 28387,
  72: 48750,
  73: 20927,
  74: 36929,
  75: 9102,
  76: 124626,
  77: 27526,
  78: 9623,
  79: 46785,
  80: 400,
  81: 880,
  82: 146599,
  83: 188588,
  84: 8447,
  85: 10534,
  86: 17414,
  87: 13997,
  88: 2086,
  89: 61548,
  90: 9095,
  91: 12158,
  92: 9283,
  93: 9208,
  94: 40154,
  95: 406,
  96: 45549,
  97: 63076,
  98: 11062,
  99: 13685,
  100: 47475,
  101: 2045,
  102: 9614,
  103: 688,
  104: 11907,
  105: 10874,
  106: 89333,
  107: 96357,
  108: 197,
  109: 103,
  110: 33542,
  111: 43566,
  112: 71754,
  113: 43612,
  114: 51352,
  115: 16934,
  116: 10324,
  117: 78406,
  118: 55731,
  119: 32119,
  120: 11066,
  121: 11104,
  122: 37975,
  123: 2074,
  124: 27793,
  125: 44284,
  126: 290157,
  127: 110972,
  128: 32622,
  129: 73067,
  130: 11863,
  131: 55475,
  132: 124636,
  133: 9101,
  134: 123360,
  135: 5757,
  136: 39428,
  137: 124639,
  138: 9302,
  139: 11000,
  140: 249882,
  141: 16388,
  142: 9737,
  143: 30765,
  144: 10474,
  145: 22279,
  146: 30157,
  147: 568,
  148: 11780,
  149: 34996,
  150: 414,
  151: 649,
  152: 1873,
  153: 5894,
  154: 1775,
  155: 8839,
  156: 20649,
  157: 10329,
  158: 8963,
  159: 26564,
  160: 8068,
  161: 8512,
  162: 1572,
  163: 13552,
  164: 259209,
  165: 6520,
  166: 9073,
  167: 10428,
  168: 17447,
  169: 9886,
  170: 9482,
  171: 19326,
  172: 9344,
  173: 9071,
  174: 8973,
  175: 15730,
  176: 47608,
  177: 2293,
  178: 9070,
  179: 68274,
  180: 48787,
  181: 34574,
  182: 1642,
  183: 11472,
  184: 36196,
  185: 11980,
  186: 58372,
  187: 32646,
  188: 10533,
  189: 56088,
  190: 10802,
  191: 10149,
  192: 18402,
  193: 9348,
  194: 139408,
  195: 281,
  196: 5967,
  197: 79593,
  198: 47939,
  199: 36834,
  200: 9090,
  201: 3512,
  202: 52856,
  203: 77350,
  204: 9560,
  205: 9804,
  206: 31611,
  207: 65796,
  208: 49805,
  209: 26258,
  210: 50797,
  211: 19155,
  212: 76,
  213: 11017,
  214: 37141,
  215: 9382,
  216: 6715,
  217: 18256,
  218: 22625,
  219: 2292,
  220: 1909,
  221: 8984,
  222: 61813,
  223: 4954,
  224: 62488,
  225: 10531,
  226: 11929,
  227: 8467,
  228: 10451,
  229: 20156,
  230: 18395,
  231: 522,
  232: 397,
  233: 10525,
  234: 27985,
  235: 15789,
  236: 27303,
  237: 21183,
  238: 10954,
  239: 47867,
  240: 43475,
  241: 72031,
  242: 14275,
  243: 1024,
  244: 17207,
  245: 13701,
  246: 14819,
  247: 32631,
  248: 11777,
  249: 628,
  250: 87729,
  251: 18713,
  252: 6280,
  253: 9061,
  254: 37108,
  255: 6071,
  256: 11,
  257: 9587,
  258: 19101,
  259: 49980,
  260: 17961,
  261: 18183,
  262: 4476,
  263: 11008,
  264: 47504,
  265: 32325,
  266: 43742,
  267: 28313,
  268: 11318,
  269: 3036,
  270: 40490,
  271: 24070,
  272: 8986,
  273: 10510,
  274: 17402,
  275: 38722,
  276: 8438,
  277: 11593,
  278: 1945,
  279: 39310,
  280: 109560,
  281: 56428,
  282: 63105,
  283: 131957,
  284: 241,
  285: 9058,
  286: 527,
  287: 18220,
  288: 6950,
  289: 101,
  290: 63020,
  291: 2307,
  292: 680,
  293: 41478,
  294: 25296,
  295: 40156,
  296: 11450,
  297: 30304,
  298: 10452,
  299: 12106,
  300: 161495,
  301: 3586,
  302: 110,
  303: 108,
  304: 109,
  305: 159185,
  306: 36357,
  307: 92769,
  308: 28033,
  309: 22586,
  310: 14334,
  311: 2636,
  312: 2164,
  313: 11395,
  314: 278,
  315: 9905,
  316: 87078,
  317: 12527,
  318: 20306,
  319: 36614,
  320: 27993,
  321: 31439,
  322: 9067,
  323: 9059,
  324: 193,
  325: 25066,
  326: 46797,
  327: 12122,
  328: 11381,
  329: 32636,
  330: 36141,
  331: 95963,
  332: 1587,
  333: 9271,
  334: 2064,
  335: 19855,
  336: 60855,
  337: 236,
  338: 48287,
  339: 3049,
  340: 2759,
  341: 12635,
  342: 10497,
  343: 11382,
  344: 9331,
  345: 10731,
  346: 10464,
  347: 34152,
  348: 9495,
  349: 29973,
  350: 888,
  351: 13,
  352: 712,
  353: 16295,
  354: 48992,
  355: 10879,
  356: 10660,
  357: 10714,
  358: 41647,
  359: 8587,
  360: 1689,
  361: 11596,
  362: 854,
  363: 9359,
  364: 23333,
  365: 36593,
  366: 12280,
  367: 2788,
  368: 10427,
  369: 11011,
  370: 49803,
  371: 8987,
  372: 1637,
  373: 15128,
  374: 8831,
  375: 36955,
  376: 10449,
  377: 10395,
  378: 12160,
  379: 40480,
  380: 52038,
  381: 29444,
  382: 26352,
  383: 39953,
  384: 41580,
  385: 315,
  386: 22067,
  387: 18242,
  388: 11667,
  389: 32502,
  390: 267188,
  391: 28732,
  392: 75555,
  393: 42981,
  394: 278939,
  395: 291731,
  396: 226229,
  397: 203119,
  398: 172923,
  399: 316098,
  400: 8011,
  401: 171857,
  402: 2654,
  403: 18069,
  404: 19092,
  405: 2758,
  406: 38129,
  407: 10436,
  408: 13595,
  409: 46094,
  410: 9409,
  411: 11853,
  412: 16771,
  413: 46924,
  414: 11041,
  415: 306,
  416: 14522,
  417: 26203,
  418: 178,
  419: 19819,
  420: 57834,
  421: 4722,
  422: 18215,
  423: 1607,
  424: 26391,
  425: 117553,
  426: 6075,
  427: 11310,
  428: 18658,
  429: 9350,
  430: 9612,
  431: 2124,
  432: 26261,
  433: 19176,
  434: 49299,
  435: 11566,
  436: 9571,
  437: 9739,
  438: 24257,
  439: 34444,
  440: 26141,
  441: 10997,
  442: 50463,
  443: 10443,
  444: 20239,
  445: 16297,
  446: 18551,
  447: 25440,
  448: 9024,
  449: 37233,
  450: 1634,
  451: 13815,
  452: 5503,
  453: 35588,
  454: 2087,
  455: 41579,
  456: 18620,
  457: 41006,
  458: 4916,
  459: 2019,
  460: 31642,
  461: 9255,
  462: 26271,
  463: 10612,
  464: 2259,
  465: 16097,
  466: 11934,
  467: 106143,
  468: 12475,
  469: 9386,
  470: 7984,
  471: 59930,
  472: 15765,
  473: 31643,
  474: 6,
  475: 329,
  476: 10909,
  477: 507,
  478: 34024,
  479: 29918,
  480: 9593,
  481: 42580,
  482: 22317,
  483: 1413,
  484: 12121,
  485: 2246,
  486: 10502,
  487: 10440,
  488: 9516,
  489: 2320,
  490: 5879,
  491: 83718,
  492: 11971,
  493: 2625,
  494: 31911,
  495: 788,
  496: 21450,
  497: 11231,
  498: 41588,
  499: 10447,
  500: 31586,
  501: 9300,
  502: 9559,
  503: 9800,
  504: 713,
  505: 8291,
  506: 18133,
  507: 25557,
  508: 22588,
  509: 10872,
  510: 1245,
  511: 11858,
  512: 7007,
  513: 10467,
  514: 5550,
  515: 8005,
  516: 2088,
  517: 10412,
  518: 47889,
  519: 14534,
  520: 56583,
  521: 41878,
  522: 424,
  523: 35233,
  524: 14291,
  525: 103413,
  526: 11236,
  527: 11592,
  528: 8850,
  529: 10445,
  530: 695,
  531: 43535,
  532: 12519,
  533: 23210,
  534: 858,
  535: 867,
  536: 78,
  537: 13203,
  538: 10442,
  539: 11074,
  540: 33367,
  541: 9607,
  542: 17585,
  543: 9057,
  544: 20967,
  545: 10635,
  546: 9479,
  547: 10057,
  548: 11969,
  549: 41590,
  550: 319,
  551: 26408,
  552: 15139,
  553: 161158,
  554: 218473,
  555: 85247,
  556: 11446,
  557: 51980,
  558: 24405,
  559: 11655,
  560: 11800,
  561: 8223,
  562: 14587,
  563: 31504,
  564: 41653,
  565: 53185,
  566: 95743,
  567: 23637,
  568: 17600,
  569: 10897,
  570: 349394,
  571: 21352,
  572: 68806,
  573: 37345,
  574: 32562,
  575: 47507,
  576: 25403,
  577: 124304,
  578: 9066,
  579: 771,
  580: 251,
  581: 812,
  582: 280,
  583: 581,
  584: 80350,
  585: 268,
  586: 274,
  587: 408,
  588: 10020,
  589: 10895,
  590: 114,
  591: 41043,
  592: 576,
  593: 15477,
  594: 59146,
  595: 124472,
  596: 30528,
  597: 7300,
  598: 10824,
  599: 261246,
  600: 275,
  601: 25059,
  602: 11827,
  603: 8766,
  604: 23570,
  605: 47333,
  606: 54850,
  607: 51242,
  608: 10112,
  609: 4307,
  610: 46029,
  611: 32308,
  612: 88893,
  613: 52873,
  614: 123505,
  615: 340210,
  616: 44281,
  617: 28121,
  618: 12520,
  619: 1592,
  620: 166901,
  621: 36447,
  622: 19042,
  623: 38884,
  624: 47449,
  625: 36259,
  626: 41852,
  627: 40926,
  628: 9099,
  629: 2021,
  630: 61752,
  631: 10988,
  632: 11479,
  633: 398959,
  634: 287305,
  635: 339428,
  636: 12652,
  637: 10684,
  638: 954,
  639: 68445,
  640: 18989,
  641: 10801,
  642: 54285,
  643: 8840,
  644: 278978,
  645: 124625,
  646: 11107,
  647: 16417,
  648: 70934,
  649: 10363,
  650: 161070,
  651: 10539,
  652: 10543,
  653: 18414,
  654: 47502,
  655: 11902,
  656: 27098,
  657: 25087,
  658: 5801,
  659: 896,
  660: 3065,
  661: 318177,
  662: 2300,
  663: 8069,
  664: 288173,
  665: 187851,
  666: 27768,
  667: 221917,
  668: 8072,
  669: 35797,
  670: 88030,
  671: 185191,
  672: 83857,
  673: 33245,
  674: 124460,
  675: 27281,
  676: 105045,
  677: 40001,
  678: 29621,
  679: 117730,
  680: 20762,
  681: 37144,
  682: 48260,
  683: 12656,
  684: 38867,
  685: 277270,
  686: 25969,
  687: 44103,
  688: 753,
  689: 43634,
  690: 9103,
  691: 90214,
  692: 29649,
  693: 10990,
  694: 8866,
  695: 12233,
  696: 23449,
  697: 36355,
  698: 37667,
  699: 90148,
  700: 922,
  701: 11876,
  702: 52633,
  703: 62364,
  704: 11687,
  705: 9304,
  706: 73183,
  707: 131232,
  708: 9100,
  709: 20759,
  710: 46063,
  711: 365371,
  712: 32513,
  713: 40651,
  714: 36915,
  715: 40507,
  716: 9802,
  717: 25697,
  718: 21588,
  719: 664,
  720: 11867,
  721: 47119,
  722: 314352,
  723: 9323,
  724: 10280,
  725: 10535,
  726: 124613,
  727: 532,
  728: 26744,
  729: 16299,
  730: 10547,
  731: 245268,
  732: 935,
  733: 55613,
  734: 215107,
  735: 41007,
  736: 35645,
  737: 110465,
  738: 255546,
  739: 40751,
  740: 275096,
  741: 85778,
  742: 11101,
  743: 9826,
  744: 9879,
  745: 63564,
  746: 22621,
  747: 7095,
  748: 26890,
  749: 46732,
  750: 124633,
  751: 202425,
  752: 196940,
  753: 77771,
  754: 181083,
  755: 41225,
  756: 188589,
  757: 87190,
  758: 627,
  759: 32872,
  760: 602,
  761: 14553,
  762: 9566,
  763: 10545,
  764: 9894,
  765: 11543,
  766: 9268,
  767: 52059,
  768: 9327,
  769: 123763,
  770: 81949,
  771: 42005,
  772: 124306,
  773: 183955,
  774: 44535,
  775: 44495,
  776: 78285,
  777: 11228,
  778: 10779,
  779: 26748,
  780: 38223,
  781: 9294,
  782: 49963,
  783: 11363,
  784: 1645,
  785: 31546,
  786: 77056,
  787: 36344,
  788: 18550,
  789: 11511,
  790: 172198,
  791: 34170,
  792: 281085,
  793: 109478,
  794: 124645,
  795: 12606,
  796: 69895,
  797: 35206,
  798: 151489,
  799: 4837,
  800: 12632,
  801: 9098,
  802: 282919,
  803: 124614,
  804: 18975,
  805: 11962,
  806: 2925,
  807: 28628,
  808: 3595,
  809: 9308,
  810: 92381,
  811: 18555,
  812: 12123,
  813: 10830,
  814: 3573,
  815: 10546,
  816: 18862,
  817: 31417,
  818: 9431,
  819: 124619,
  820: 297645,
  821: 48144,
  822: 46986,
  823: 144982,
  824: 47907,
  825: 10061,
  826: 36266,
  827: 549,
  828: 10478,
  829: 66634,
  830: 116690,
  831: 213917,
  832: 145925,
  833: 100914,
  834: 238,
  835: 159,
  836: 11134,
  837: 88224,
  838: 132641,
  839: 42758,
  840: 9303,
  841: 23945,
  842: 37820,
  843: 22479,
  844: 9054,
  845: 241058,
  846: 11985,
  847: 10232,
  848: 59569,
  849: 410921,
  850: 38955,
  851: 110513,
  852: 114089,
  853: 11015,
  854: 9306,
  855: 12559,
  856: 58770,
  857: 124851,
  858: 3587,
  859: 10723,
  860: 56077,
  861: 19004,
  862: 101230,
  863: 253632,
  864: 10987,
  865: 44705,
  866: 20318,
  867: 43596,
  868: 79782,
  869: 26933,
  870: 27854,
  871: 981,
  872: 872,
  873: 2769,
  874: 13320,
  875: 164,
  876: 426,
  877: 567,
  878: 3078,
  879: 13528,
  880: 28288,
  881: 213,
  882: 284,
  883: 239,
  884: 4808,
  885: 289,
  886: 963,
  887: 11113,
  888: 6620,
  889: 804,
  890: 26531,
  891: 909,
  892: 630,
  893: 770,
  894: 31044,
  895: 599,
  896: 15,
  897: 62,
  898: 121357,
  899: 705,
  900: 22490,
  901: 223,
  902: 25670,
  903: 303,
  904: 4174,
  905: 8356,
  906: 381,
  907: 20758,
  908: 29376,
  909: 1859,
  910: 18299,
  911: 17281,
  912: 64382,
  913: 10907,
  914: 32093,
  915: 1939,
  916: 22292,
  917: 3598,
  918: 3080,
  919: 198,
  920: 13562,
  921: 1712,
  922: 220,
  923: 3529,
  924: 3085,
  925: 2897,
  926: 1585,
  927: 3083,
  928: 900,
  929: 43795,
  930: 85638,
  931: 50001,
  932: 43905,
  933: 22688,
  934: 23114,
  935: 26378,
  936: 40206,
  937: 22356,
  938: 260,
  939: 43488,
  940: 22613,
  941: 10331,
  942: 488,
  943: 22733,
  944: 261,
  945: 57575,
  946: 32574,
  947: 22657,
  948: 76464,
  949: 22649,
  950: 176841,
  951: 125587,
  952: 39448,
  953: 52855,
  954: 39940,
  955: 172868,
  956: 85328,
  957: 124632,
  958: 11076,
  959: 63945,
  960: 58985,
  961: 890,
  962: 10861,
  963: 1770,
  964: 44465,
  965: 2033,
  966: 18203,
  967: 9333,
  968: 47260,
  969: 9400,
  970: 9401,
  971: 12241,
  972: 25739,
  973: 161806,
  974: 11306,
  975: 9625,
  976: 10680,
  977: 6346,
  978: 18660,
  979: 35115,
  980: 14821,
  981: 14136,
  982: 10869,
  983: 22660,
  984: 19186,
  985: 31102,
  986: 6878,
  987: 15944,
  988: 18444,
  989: 20723,
  990: 173,
  991: 864,
  992: 24795,
  993: 11224,
  994: 81310,
  995: 15947,
  996: 9078,
  997: 29682,
  998: 8367,
  999: 433,
  ...},
 'title': {0: 'Toy Story',
  1: 'Jumanji',
  2: 'Grumpier Old Men',
  3: 'Waiting to Exhale',
  4: 'Father of the Bride Part II',
  5: 'Heat',
  6: 'Sabrina',
  7: 'Tom and Huck',
  8: 'Sudden Death',
  9: 'GoldenEye',
  10: 'The American President',
  11: 'Dracula: Dead and Loving It',
  12: 'Balto',
  13: 'Nixon',
  14: 'Cutthroat Island',
  15: 'Casino',
  16: 'Sense and Sensibility',
  17: 'Four Rooms',
  18: 'Ace Ventura: When Nature Calls',
  19: 'Money Train',
  20: 'Get Shorty',
  21: 'Copycat',
  22: 'Assassins',
  23: 'Powder',
  24: 'Leaving Las Vegas',
  25: 'Othello',
  26: 'Now and Then',
  27: 'Persuasion',
  28: 'The City of Lost Children',
  29: 'Shanghai Triad',
  30: 'Dangerous Minds',
  31: 'Twelve Monkeys',
  32: 'Wings of Courage',
  33: 'Babe',
  34: 'Carrington',
  35: 'Dead Man Walking',
  36: 'Across the Sea of Time',
  37: 'It Takes Two',
  38: 'Clueless',
  39: 'Cry, the Beloved Country',
  40: 'Richard III',
  41: 'Dead Presidents',
  42: 'Restoration',
  43: 'Mortal Kombat',
  44: 'To Die For',
  45: 'How To Make An American Quilt',
  46: 'Se7en',
  47: 'Pocahontas',
  48: 'When Night Is Falling',
  49: 'The Usual Suspects',
  50: 'Guardian Angel',
  51: 'Mighty Aphrodite',
  52: 'Lamerica',
  53: 'The Big Green',
  54: 'Georgia',
  55: 'Kids of the Round Table',
  56: 'Home for the Holidays',
  57: 'The Postman',
  58: 'The Confessional',
  59: 'The Indian in the Cupboard',
  60: 'Eye for an Eye',
  61: "Mr. Holland's Opus",
  62: "Don't Be a Menace to South Central While Drinking Your Juice in the Hood",
  63: 'Two If by Sea',
  64: 'Bio-Dome',
  65: 'Lawnmower Man 2: Beyond Cyberspace',
  66: 'Two Bits',
  67: 'French Twist',
  68: 'Friday',
  69: 'From Dusk Till Dawn',
  70: 'Fair Game',
  71: 'Kicking and Screaming',
  72: 'Les Miserables',
  73: 'Bed of Roses',
  74: 'Big Bully',
  75: 'Screamers',
  76: 'Nico Icon',
  77: 'The Crossing Guard',
  78: 'The Juror',
  79: 'The White Balloon',
  80: "Things to Do in Denver When You're Dead",
  81: "Antonia's Line",
  82: 'Once Upon a Time... When We Were Colored',
  83: 'Last Summer in the Hamptons',
  84: 'Angels and Insects',
  85: 'White Squall',
  86: 'Dunston Checks In',
  87: 'Black Sheep',
  88: 'Nick of Time',
  89: 'The Journey of August King',
  90: 'Mary Reilly',
  91: 'Vampire in Brooklyn',
  92: 'Beautiful Girls',
  93: 'Broken Arrow',
  94: "A Midwinter's Tale",
  95: 'La Haine',
  96: 'Shopping',
  97: 'Heidi Fleiss: Hollywood Madam',
  98: 'City Hall',
  99: 'Bottle Rocket',
  100: 'Mr. Wrong',
  101: 'Unforgettable',
  102: 'Happy Gilmore',
  103: 'The Bridges of Madison County',
  104: 'Nobody Loves Me',
  105: 'Muppet Treasure Island',
  106: 'Catwalk',
  107: 'Headless Body in Topless Bar',
  108: 'Braveheart',
  109: 'Taxi Driver',
  110: 'Rumble in the Bronx',
  111: 'Before and After',
  112: "Margaret's Museum",
  113: 'Happiness Is in the Field',
  114: 'Anne Frank Remembered',
  115: "The Young Poisoner's Handbook",
  116: 'If Lucy Fell',
  117: 'Steal Big Steal Little',
  118: 'Race the Sun',
  119: 'The Boys of St. Vincent',
  120: 'Boomerang',
  121: 'Chungking Express',
  122: 'The Star Maker',
  123: 'Flirting with Disaster',
  124: 'The Neverending Story III: Escape from Fantasia',
  125: 'The Silences of the Palace',
  126: "Jupiter's Wife",
  127: 'Pie in the Sky',
  128: 'Angela',
  129: 'Frankie Starlight',
  130: 'Jade',
  131: 'Nueba Yol',
  132: 'Sonic Outlaws',
  133: 'Down Periscope',
  134: 'From the Journals of Jean Seberg',
  135: 'Man of the Year',
  136: 'The Neon Bible',
  137: 'Target',
  138: 'Up Close & Personal',
  139: 'The Birdcage',
  140: 'Virgin Mary',
  141: 'The Brothers McMullen',
  142: 'Bad Boys',
  143: 'The Amazing Panda Adventure',
  144: 'The Basketball Diaries',
  145: 'An Awfully Big Adventure',
  146: 'Amateur',
  147: 'Apollo 13',
  148: 'Rob Roy',
  149: 'The Addiction',
  150: 'Batman Forever',
  151: 'Belle de Jour',
  152: 'Beyond Rangoon',
  153: 'Blue in the Face',
  154: 'Canadian Bacon',
  155: 'Casper',
  156: 'Clockers',
  157: 'Congo',
  158: 'Crimson Tide',
  159: 'Crumb',
  160: 'Desperado',
  161: 'Devil in a Blue Dress',
  162: 'Die Hard: With a Vengeance',
  163: 'The Doom Generation',
  164: 'Feast of July',
  165: 'First Knight',
  166: 'Free Willy 2 - The Adventure Home',
  167: 'Hackers',
  168: 'Jeffrey',
  169: 'Johnny Mnemonic',
  170: 'Judge Dredd',
  171: 'Jury Duty',
  172: 'Kids',
  173: 'Living in Oblivion',
  174: 'Lord of Illusions',
  175: 'Love & Human Remains',
  176: 'Mad Love',
  177: 'Mallrats',
  178: 'Mighty Morphin Power Rangers: The Movie',
  179: 'Moonlight and Valentino',
  180: 'Mute Witness',
  181: 'Nadja',
  182: 'The Net',
  183: 'Nine Months',
  184: 'Party Girl',
  185: 'The Prophecy',
  186: 'Reckless',
  187: 'Safe',
  188: 'The Scarlet Letter',
  189: 'The Show',
  190: 'Showgirls',
  191: 'Smoke',
  192: 'Something to Talk About',
  193: 'Species',
  194: 'The Stars Fell on Henrietta',
  195: 'Strange Days',
  196: 'The Umbrellas of Cherbourg',
  197: 'The Tie That Binds',
  198: 'Three Wishes',
  199: 'Total Eclipse',
  200: 'To Wong Foo, Thanks for Everything! Julie Newmar',
  201: 'Under Siege 2: Dark Territory',
  202: 'Unstrung Heroes',
  203: 'Unzipped',
  204: 'A Walk in the Clouds',
  205: 'Waterworld',
  206: "White Man's Burden",
  207: 'Wild Bill',
  208: 'The Browning Version',
  209: 'Bushwhacked',
  210: 'Burnt by the Sun',
  211: 'Before the Rain',
  212: 'Before Sunrise',
  213: 'Billy Madison',
  214: 'The Babysitter',
  215: 'Boys on the Side',
  216: 'The Cure',
  217: 'Castle Freak',
  218: 'Circle of Friends',
  219: 'Clerks',
  220: 'Don Juan DeMarco',
  221: 'Disclosure',
  222: 'Dream Man',
  223: 'Drop Zone',
  224: 'Destiny Turns on the Radio',
  225: 'Death and the Maiden',
  226: 'Dolores Claiborne',
  227: 'Dumb and Dumber',
  228: 'Eat Drink Man Woman',
  229: 'Exotica',
  230: 'Exit to Eden',
  231: 'Ed Wood',
  232: 'French Kiss',
  233: 'Forget Paris',
  234: 'Far from Home: The Adventures of Yellow Dog',
  235: 'A Goofy Movie',
  236: 'Hideaway',
  237: 'Fluke',
  238: 'Farinelli',
  239: 'Gordy',
  240: 'Gumby: The Movie',
  241: 'The Glass Shield',
  242: 'Hoop Dreams',
  243: 'Heavenly Creatures',
  244: 'Houseguest',
  245: 'Immortal Beloved',
  246: 'Heavyweights',
  247: 'The Hunted',
  248: 'I.Q.',
  249: 'Interview with the Vampire',
  250: 'Jefferson in Paris',

In [67]:
pickle.dump(similarity,open('similarity.pkl','wb'))